# ba_tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module BaTester
  # A integer based enum representing a Suite in a game of cards
  class SuiteCodeEnum
    SUITE_CODE_ENUM = [
      # TODO: Write general description for HEARTS
      HEARTS = 1,

      # TODO: Write general description for SPADES
      SPADES = 2,

      # TODO: Write general description for CLUBS
      CLUBS = 3,

      # TODO: Write general description for DIAMONDS
      DIAMONDS = 4
    ].freeze
  end
end
