# ba_tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'ba_tester'
require_relative '../test_helper'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include BaTester

  # Create configuration and set any test parameters
  CONFIG = Configuration.new(basic_auth_user_name: 'Zeeshan',
                             basic_auth_password: 'bhai_99',
                             environment: Environment::TESTING)
end
