# ba_tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module BaTester
  #  ba_tester client class.
  class Client
    attr_reader :config

    # Access to client controller.
    # @return [APIController] Returns the controller instance.
    def client
      @client ||= APIController.new config
    end

    def initialize(http_client_instance: nil, timeout: 60, max_retries: 0,
                   retry_interval: 1, backoff_factor: 2,
                   retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                   retry_methods: %i[get put],
                   environment: Environment::TESTING, port: '80',
                   suites: SuiteCodeEnum::HEARTS,
                   basic_auth_user_name: 'TODO: Replace',
                   basic_auth_password: 'TODO: Replace', config: nil)
      @config = if config.nil?
                  Configuration.new(http_client_instance: http_client_instance,
                                    timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    retry_statuses: retry_statuses,
                                    retry_methods: retry_methods,
                                    environment: environment, port: port,
                                    suites: suites,
                                    basic_auth_user_name: basic_auth_user_name,
                                    basic_auth_password: basic_auth_password)
                else
                  config
                end
    end
  end
end
