# ba_tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module BaTester
  # An enum for SDK environments.
  class Environment
    ENVIRONMENT = [
      PRODUCTION = 'production'.freeze,
      TESTING = 'testing'.freeze
    ].freeze
  end

  # An enum for API servers.
  class Server
    SERVER = [
      DEFAULT = 'default'.freeze,
      AUTH_SERVER = 'auth server'.freeze
    ].freeze
  end

  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # The attribute readers for properties.
    attr_reader :http_client, :http_client_instance, :timeout, :max_retries, :retry_interval,
                :backoff_factor, :retry_statuses, :retry_methods, :environment, :port, :suites,
                :basic_auth_user_name, :basic_auth_password

    class << self
      attr_reader :environments
    end

    def initialize(http_client_instance: nil, timeout: 60, max_retries: 0,
                   retry_interval: 1, backoff_factor: 2,
                   retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                   retry_methods: %i[get put],
                   environment: Environment::TESTING, port: '80',
                   suites: SuiteCodeEnum::HEARTS,
                   basic_auth_user_name: 'TODO: Replace',
                   basic_auth_password: 'TODO: Replace')
      # The Http Client passed from the sdk user for making requests
      @http_client_instance = http_client_instance

      # The value to use for connection timeout
      @timeout = timeout

      # The number of times to retry an endpoint call if it fails
      @max_retries = max_retries

      # Pause in seconds between retries
      @retry_interval = retry_interval

      # The amount to multiply each successive retry's interval amount
      # by in order to provide backoff
      @backoff_factor = backoff_factor

      # A list of HTTP statuses to retry
      @retry_statuses = retry_statuses

      # A list of HTTP methods to retry
      @retry_methods = retry_methods

      # Current API environment
      @environment = String(environment)

      # port value
      @port = port

      # suites value
      @suites = suites

      # The username to use with basic authentication
      @basic_auth_user_name = basic_auth_user_name

      # The password to use with basic authentication
      @basic_auth_password = basic_auth_password

      # The Http Client to use for making requests.
      @http_client = create_http_client
    end

    def clone_with(http_client_instance: nil, timeout: nil, max_retries: nil,
                   retry_interval: nil, backoff_factor: nil,
                   retry_statuses: nil, retry_methods: nil, environment: nil,
                   port: nil, suites: nil, basic_auth_user_name: nil,
                   basic_auth_password: nil)
      http_client_instance ||= self.http_client_instance
      timeout ||= self.timeout
      max_retries ||= self.max_retries
      retry_interval ||= self.retry_interval
      backoff_factor ||= self.backoff_factor
      retry_statuses ||= self.retry_statuses
      retry_methods ||= self.retry_methods
      environment ||= self.environment
      port ||= self.port
      suites ||= self.suites
      basic_auth_user_name ||= self.basic_auth_user_name
      basic_auth_password ||= self.basic_auth_password

      Configuration.new(http_client_instance: http_client_instance,
                        timeout: timeout, max_retries: max_retries,
                        retry_interval: retry_interval,
                        backoff_factor: backoff_factor,
                        retry_statuses: retry_statuses,
                        retry_methods: retry_methods, environment: environment,
                        port: port, suites: suites,
                        basic_auth_user_name: basic_auth_user_name,
                        basic_auth_password: basic_auth_password)
    end

    def create_http_client
      FaradayClient.new(timeout: timeout, max_retries: max_retries,
                        retry_interval: retry_interval,
                        backoff_factor: backoff_factor,
                        retry_statuses: retry_statuses,
                        retry_methods: retry_methods,
                        http_client_instance: http_client_instance)
    end

    # All the environments the SDK can run in.
    ENVIRONMENTS = {
      Environment::PRODUCTION => {
        Server::DEFAULT => 'http://apimatic.hopto.org:{suites}',
        Server::AUTH_SERVER => 'http://apimaticauth.hopto.org:3000'
      },
      Environment::TESTING => {
        Server::DEFAULT => 'http://localhost:3000',
        Server::AUTH_SERVER => 'http://apimaticauth.xhopto.org:3000'
      }
    }.freeze

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def get_base_uri(server = Server::DEFAULT)
      parameters = {
        'port' => { 'value' => port, 'encode' => false },
        'suites' => { 'value' => suites, 'encode' => false }
      }
      APIHelper.append_url_with_template_parameters(
        ENVIRONMENTS[environment][server], parameters
      )
    end
  end
end
